[package]
name = "svix-server"
version = "0.48.0"
license = "MIT"
description = "Svix webhooks server"

authors = ["Svix Inc. <oss@svix.com>"]
homepage = "https://www.svix.com"
repository = "https://github.com/svix/svix-webhooks"
readme = "../README.md"
edition = "2021"
publish = false

[dependencies]
svix-server_derive = { path = "../svix-server_derive" }

svix-ksuid = "^0.5.1"
dotenv = "0.15.0"
getrandom = "0.2.4"
hmac-sha256 = "1"
clap = { version = "3.0.10", features = ["derive"] }
axum = { version = "0.4.4", features = ["headers"] }
base64 = "0.13.0"
hyper = { version = "0.14.16", features = ["full"] }
tokio = { version = "1.15.0", features = ["full"] }
tower = "0.4.11"
tower-http = { version = "0.2.0", features = ["trace"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
serde_urlencoded = "0.7.1"
num_enum = "0.5.6"
regex = "1.5.4"
lazy_static = "1.4.0"
figment = { version = "0.10", features = ["toml", "env"] }
tracing = "0.1.29"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
validator = { version = "0.14.0", features = ["derive"] }
jwt-simple = "0.10.8"
chrono = { version="0.4.19", features = ["serde"] }
reqwest = { version = "0.11.9", features = ["json", "rustls-tls", "trust-dns"], default-features = false }
bb8 = "0.7.1"
bb8-redis = "0.10.1"
redis = { version = "0.21.5", features = ["tokio-comp"] }
# sea orm
sea-orm = { version = "0.5.0", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ], default-features = false }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "migrate" ] }
