name: Server CI

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'

jobs:
  check:
    # Run `cargo check` first to ensure that the pushed code at least compiles.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v1
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --manifest-path server/Cargo.toml --all --all-targets --all-features
    - name: rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path server/Cargo.toml --all -- --check

  test-versions:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - uses: Swatinem/rust-cache@v1
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path server/Cargo.toml  --all --all-features --all-targets

#  deny-check:
#    name: cargo-deny check
#    runs-on: ubuntu-latest
#    continue-on-error: ${{ matrix.checks == 'advisories' }}
#    strategy:
#      matrix:
#        checks:
#          - advisories
#          - bans licenses sources
#    steps:
#      - uses: actions/checkout@v2
#      - uses: EmbarkStudios/cargo-deny-action@v1
#        with:
#          command: check ${{ matrix.checks }}
#          arguments: --all-features --manifest-path axum/Cargo.toml
